2019-10-05 21:56:55,866 - ERROR - myapi.py[:46] - Delete user failed!Err:(sqlite3.OperationalError) no such table: users
[SQL: INSERT INTO users (name, gender, campus, grade, college, major, address, phone, email, first_choice, second_choice, introduction, create_time, state) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('123', '123', '123', '123', '123', '123', '123', '123', '123@qq.com', '123', '123', '123', '2019-10-05 21:56:55.865742', 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-05 22:17:24,428 - ERROR - myapi.py[:180] - Query all users failed!Err:(sqlite3.OperationalError) no such table: users
[SQL: SELECT users.id AS users_id, users.name AS users_name, users.gender AS users_gender, users.campus AS users_campus, users.grade AS users_grade, users.college AS users_college, users.major AS users_major, users.address AS users_address, users.phone AS users_phone, users.email AS users_email, users.first_choice AS users_first_choice, users.second_choice AS users_second_choice, users.introduction AS users_introduction, users.create_time AS users_create_time, users.state AS users_state 
FROM users 
WHERE 1 = 1 ORDER BY users.create_time]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-05 22:17:24,429 - ERROR - myapi.py[:46] - Delete user failed!Err:(sqlite3.OperationalError) no such table: users
[SQL: INSERT INTO users (name, gender, campus, grade, college, major, address, phone, email, first_choice, second_choice, introduction, create_time, state) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('123', '123', '123', '123', '123', '123', '123', '123', 'zxcxzcz@qq.com', '123', '123', '123', '2019-10-05 22:17:24.427013', 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-05 22:19:51,207 - ERROR - myapi.py[:46] - Delete user failed!Err:(sqlite3.OperationalError) no such table: users
[SQL: INSERT INTO users (name, gender, campus, grade, college, major, address, phone, email, first_choice, second_choice, introduction, create_time, state) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('123', '123', '123', '123', '123', '123', '123', '123', 'zxcxzcz@qq.com', '132', '123', '123', '2019-10-05 22:19:51.204083', 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-05 22:19:51,208 - ERROR - myapi.py[:180] - Query all users failed!Err:(sqlite3.OperationalError) no such table: users
[SQL: SELECT users.id AS users_id, users.name AS users_name, users.gender AS users_gender, users.campus AS users_campus, users.grade AS users_grade, users.college AS users_college, users.major AS users_major, users.address AS users_address, users.phone AS users_phone, users.email AS users_email, users.first_choice AS users_first_choice, users.second_choice AS users_second_choice, users.introduction AS users_introduction, users.create_time AS users_create_time, users.state AS users_state 
FROM users 
WHERE 1 = 1 ORDER BY users.create_time]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-05 22:21:42,395 - ERROR - myapi.py[:180] - Query all users failed!Err:(sqlite3.OperationalError) no such table: users
[SQL: SELECT users.id AS users_id, users.name AS users_name, users.gender AS users_gender, users.campus AS users_campus, users.grade AS users_grade, users.college AS users_college, users.major AS users_major, users.address AS users_address, users.phone AS users_phone, users.email AS users_email, users.first_choice AS users_first_choice, users.second_choice AS users_second_choice, users.introduction AS users_introduction, users.create_time AS users_create_time, users.state AS users_state 
FROM users 
WHERE 1 = 1 ORDER BY users.create_time]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-05 22:21:42,395 - ERROR - myapi.py[:46] - Delete user failed!Err:(sqlite3.OperationalError) no such table: users
[SQL: INSERT INTO users (name, gender, campus, grade, college, major, address, phone, email, first_choice, second_choice, introduction, create_time, state) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('123', '123', '123', '123', '123', '123', '123', '123', 'zxcxzcz@qq.com', '123', '123', '123', '2019-10-05 22:21:42.394327', 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-05 22:22:42,701 - ERROR - myapi.py[:46] - Delete user failed!Err:'name'
2019-10-05 22:23:44,854 - ERROR - myapi.py[:46] - Delete user failed!Err:'name'
2019-10-05 22:26:42,989 - ERROR - myapi.py[:46] - Delete user failed!Err:'gender'
2019-10-05 22:29:04,319 - ERROR - myapi.py[:46] - Delete user failed!Err:'name'
2019-10-05 22:30:49,030 - ERROR - myapi.py[:46] - Delete user failed!Err:'college'
2019-10-05 22:32:29,252 - ERROR - myapi.py[:47] - Delete user failed!Err:'name'
